/* Generated by opensource COBOL 4J 1.1.12 */
import java.io.UnsupportedEncodingException;
import jp.osscons.opensourcecobol.libcobj.*;
import jp.osscons.opensourcecobol.libcobj.common.*;
import jp.osscons.opensourcecobol.libcobj.data.*;
import jp.osscons.opensourcecobol.libcobj.exceptions.*;
import jp.osscons.opensourcecobol.libcobj.termio.*;
import jp.osscons.opensourcecobol.libcobj.call.*;
import jp.osscons.opensourcecobol.libcobj.file.*;
import jp.osscons.opensourcecobol.libcobj.ui.*;
import java.util.Optional;
import java.lang.NullPointerException;
import java.lang.IndexOutOfBoundsException;

public class test_sequential_lock implements CobolRunnable {

  private boolean initialized = false;
  private CobolModule module;
  private int entry;

  private CobolRunnable cob_unifunc;


  @Override
  public int run(CobolDataStorage... argStorages) {
    return test_sequential_lock_(0, argStorages);
  }

  @Override
  public void cancel() {
    test_sequential_lock_(-1);
  }

  @Override
  public boolean isActive() {
    return false;
  }

  public CobolResultSet execute () {
    int returnCode = run_module(0);
    return new CobolResultSet(returnCode);
  }

  public int test_sequential_lock_ (int entry, CobolDataStorage ...argStorages) {
    this.entry = entry;
    return this.run_module(entry);
  }

  int run_module (int entry) {
    this.module = new CobolModule(null, null, null, null, 0, '.', '$', ',', 1, 1, 1, 0, null );

    /* Start of function code */

    /* CANCEL callback handling */
    if (entry < 0) {
    	if (!this.initialized) {
    		CobolDecimal.cobInitNumeric();
    		return 0;
    	}
    	h_TEST_FILE.close (0, null);
    	this.initialized = false;
    	return 0;
    }

    /* Push module stack */
    CobolModule.push (module);

    /* Initialize program */
    if (!this.initialized) {
      module.setProgramId("test_sequential_lock");

      b_RETURN_CODE.set((int)0);
      b_file_status.fillBytes('0', 2);

      h_TEST_FILE = CobolFileFactory.makeCobolFileInstance(
      /* select_name = */ "test-file",
      /* file_status = */ h_TEST_FILE_status,
      /* assign = */ c_1,
      /* record = */ f_test_file_record,
      /* record_size = */ null,
      /* record_min = */ 10,
      /* record_max = */ 10,
      /* nkeys = */ 0,
      /* keys = */ null,
      /* organization = */ (char)0,
      /* access_mode = */ (char)1,
      /* lock_mode = */ (char)2,
      /* open_mode = */ (char)0,
      /* flag_optional = */ false,
      /* last_open_mode = */ (char)0,
      /* special = */ (char)0,
      /* flag_nonexistent = */ false,
      /* flag_end_of_file = */ false,
      /* flag_begin_of_file = */ false,
      /* flag_first_read = */ (char)0,
      /* flag_read_done = */ false,
      /* flag_select_features = */ (char)1,
      /* flag_needs_nl = */ false,
      /* flag_needs_top = */ false,
      /* file_version = */ (char)0
      );

      this.initialized = true;
    }
    /* PROCEDURE DIVISION */
    try{
      CobolStopRunException.dummy();
      CobolGoBackException.dummy();
      /* Entry dispatch */
      execEntry(l_test_sequential_lock);

    } catch(CobolGoBackException e) {
      return e.getReturnCode();
    } catch(CobolStopRunException e) {
      CobolStopRunException.stopRun();
      System.exit(e.getReturnCode());
    }
    /* Pop module stack */
    CobolModule.pop();

    /* Program return */
    return b_RETURN_CODE.intValue();
  }
  public CobolControl[] contList = {
    new CobolControl(0, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_test_sequential_lock]);
      }
    },
    /* Entry test_sequential_lock */
    new CobolControl(l_test_sequential_lock, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION]);
      }
    },
    /* MAIN SECTION */
    new CobolControl(l_MAIN_SECTION, CobolControl.LabelType.section) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        return Optional.of(contList[l_MAIN_SECTION__main_procedure]);
      }
    },
    /* main-procedure */
    new CobolControl(l_MAIN_SECTION__main_procedure, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
        /* /tmp/test_sequential_lock.cbl:22: OPEN */
        {
          CobolRuntimeException.code = 0;
          {
            h_TEST_FILE.open (2, 1, f_file_status);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }
        /* /tmp/test_sequential_lock.cbl:23: DISPLAY */
        {
          CobolTerminal.display (0, 1, 2, c_2_First, f_file_status);
        }
        /* /tmp/test_sequential_lock.cbl:24: CALL */
        {
          CobolDataStorage content_1 = new CobolDataStorage(8);
          content_1.set(5L);
          CobolModule.getCurrentModule ().setParameters (c_3_5);
          CobolCallParams.callParams = 1;
          b_RETURN_CODE.set (CobolSystemRoutine.C$SLEEP (content_1));
        }
        /* /tmp/test_sequential_lock.cbl:25: CLOSE */
        {
          CobolRuntimeException.code = 0;
          {
            h_TEST_FILE.close (0, f_file_status);
          }
          if (CobolRuntimeException.code != 0)
          {
            /* PERFORM Default Error Handler */
            CobolControl.perform(contList, l_Default_Error_Handler).run();
          }
        }


        return Optional.of(CobolControl.pure());
      }
    },
    /* Default Error Handler */
    new CobolControl(l_Default_Error_Handler, CobolControl.LabelType.label) {
      public Optional<CobolControl> run() throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {

        if ((CobolFile.errorFile.flag_select_features & CobolFile.COB_SELECT_FILE_STATUS) == 0) {
        	CobolFile.defaultErrorHandle ();
        	CobolStopRunException.stopRunAndThrow (1);
        }

        return Optional.of(CobolControl.pure());
      }
    },
    CobolControl.pure()
  };
  public void execEntry(int start) throws CobolRuntimeException, CobolGoBackException, CobolStopRunException {
    Optional<CobolControl> nextLabel = Optional.of(contList[start]);
    while(nextLabel.isPresent()) {
      CobolControl section = nextLabel.get();
      nextLabel = section.run();
    }
  }

  public static void main(String[] args)
  {
    CobolUtil.cob_init(args, false);
    CobolDecimal.cobInitNumeric();
    new test_sequential_lock().test_sequential_lock_(0);
    CobolStopRunException.stopRun();
  }

  public test_sequential_lock()
  {
    init();
  }

  public void init() 
  {
    try {
      /* Data storage */

      cob_unifunc = null;

      /* PROGRAM-ID : test_sequential_lock */
      b_RETURN_CODE = new CobolDataStorage(4);	/* RETURN-CODE */
      b_test_file_record = new CobolDataStorage(10);	/* test-file_record */
      b_file_status = new CobolDataStorage(2);	/* file-status */

      /* End of data storage */


      initAttr();

      /* Fields */

      /* PROGRAM-ID : test_sequential_lock */
      f_test_file_record	= CobolFieldFactory.makeCobolField(10, b_test_file_record, a_1);	/* test-file_record */
      f_file_status	= CobolFieldFactory.makeCobolField(2, b_file_status, a_2);	/* file-status */

      /* End of fields */


      /* Constants */

      c_1	= CobolFieldFactory.makeCobolField(str_0, a_1);
      c_2_First	= CobolFieldFactory.makeCobolField(str_1_First, a_1);
      c_3_5	= CobolFieldFactory.makeCobolField(1, "5", a_3);

    } catch(NullPointerException e) {
      System.out.println("Error - NullpointerException");
    } catch(IndexOutOfBoundsException e) {
      System.out.println("Error - IndexOutOfBoundsException");
    }
  }

  private void initAttr() {
    /* Attributes */

    a_1 = new CobolFieldAttribute (33, 0, 0, 0, null);
    a_2 = new CobolFieldAttribute (16, 2, 0, 0, null);
    a_3 = new CobolFieldAttribute (16, 1, 0, 0, null);

  }

  /* Data storage */

  /* PROGRAM-ID : test_sequential_lock */
  private CobolDataStorage b_RETURN_CODE;	/* RETURN-CODE */
  private CobolDataStorage b_test_file_record;	/* test-file_record */
  private CobolDataStorage b_file_status;	/* file-status */

  /* End of data storage */


  /* Fields */

  /* PROGRAM-ID : test_sequential_lock */
  private AbstractCobolField f_test_file_record;	/* test-file_record */
  private AbstractCobolField f_file_status;	/* file-status */

  /* End of fields */


  private static AbstractCobolField f_native;

  /* Constants */

  private AbstractCobolField c_3_5;
  private AbstractCobolField c_2_First;
  private AbstractCobolField c_1;

  /* Attributes */

  private CobolFieldAttribute a_3;
  private CobolFieldAttribute a_2;
  private CobolFieldAttribute a_1;



  /* String literals */
  public static final byte[] str_1_First = CobolUtil.stringToBytes("First open status: ");
  public static final byte[] str_0 = CobolUtil.stringToBytes("./test.dat");
  /* File test-file */
  private CobolFile		h_TEST_FILE = null;
  private byte[]	h_TEST_FILE_status = new byte[4];

  /* Sections and Labels */
  private final static int l_test_sequential_lock = 1;
  private final static int l_MAIN_SECTION = 2;
  private final static int l_MAIN_SECTION__main_procedure = 3;
  private final static int l_Default_Error_Handler = 4;

}
