#!/bin/bash
cppcheck --error-exitcode=1 \
    cobj.c cobj.h codegen.c config.c error.c field.c ppparse.h reserved.c tree.c tree.h typeck.c \
    --enable=style \
    --enable=performance \
    --enable=portability \
    --suppress=unusedFunctions \
    --suppress=toomanyconfigs \
    --suppress=unusedStructMember \
    --suppress=leakNoVarFunctionCall \
    --suppress=unreadVariable
