/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.osscons.opensourcecobol.libcobj.user_util.cobj_api;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import org.junit.jupiter.api.Test;

class ApiFilesTest {

  boolean compOutputFiles(String file_name) {
    ApiFiles.javaCreate(file_name);
    try {
      return Arrays.equals(
              Files.readAllBytes(
                  Paths.get(
                      "src/test/java/jp/osscons/opensourcecobol/libcobj/user_util/cobj_api/testController.txt")),
              Files.readAllBytes(Paths.get("testController.java")))
          && Arrays.equals(
              Files.readAllBytes(
                  Paths.get(
                      "src/test/java/jp/osscons/opensourcecobol/libcobj/user_util/cobj_api/testRecord.txt")),
              Files.readAllBytes(Paths.get("testRecord.java")));
    } catch (IOException e) {
      e.printStackTrace();
      return false;
    }
  }

  @Test
  void checkOutputFiles() {
    String file_name =
        "src/test/java/jp/osscons/opensourcecobol/libcobj/user_util/cobj_api/test.json";
    assertTrue(compOutputFiles(file_name));
  }
}
