#define COB_CC           "cl.exe"
#define COB_CFLAGS       "-I c:\\opensourcecobol4j\\include\\"
#define COB_LDFLAGS      ""
#define COB_LIBS         "c:\\opensourcecobol4j\\lib\\libcob.lib"
#define COB_CONFIG_DIR   "c:\\opensourcecobol4j\\config"
#define COB_COPY_DIR     "copy"
#define COB_LIBRARY_PATH "."
#define COB_MODULE_EXT   "dll"
#define LOCALEDIR        "c:\\locale"