test:
	. ../../atconfig; . ../../atlocal; export PATH; perl /home/y-sakamoto/sample/opensourcecobol4j/tests/cobol85/report.pl
	diff /home/y-sakamoto/sample/opensourcecobol4j/tests/cobol85/IF.txt report.txt
	#. ../../atconfig; . ../../atlocal; export PATH; perl /home/y-sakamoto/sample/opensourcecobol4j/tests/cobol85/report.pl -O
	#diff /home/y-sakamoto/sample/opensourcecobol4j/tests/cobol85/IF.txt report.txt
