name: build opensource COBOL 4J using gcc 9

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies on Ubuntu 22.04
        run: |
          sudo apt update -y
          sudo apt install -y gcc-9 build-essential gettext autoconf

      - name: Checkout opensource COBOL 4J
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      
      - name: Install opensource COBOL 4J
        run: |
          ./configure --prefix=/usr/ CC=gcc-9
          make