name: build opensource COBOL 4J using gcc 9

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies on Ubuntu
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-9 build-essential gettext autoconf

      - name: Checkout opensource COBOL 4J
        uses: actions/checkout@v4
      
      - name: Install opensource COBOL 4J
        run: |
          ./configure --prefix=/usr/ CC=gcc-9
          make