name: Check workflow files

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install actionlint
        run: |
          GOBIN=$(pwd) go install github.com/rhysd/actionlint/cmd/actionlint@latest
      
      - name: Run actionlint
        run: |
          ./actionlint