name: Coverage

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  CLASSPATH: ":/usr/lib/opensourcecobol4j/libcobj.jar"

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies on Ubuntu
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential gettext autoconf bison flex gcovr

      - name: Checkout opensource COBOL 4J
        uses: actions/checkout@v7
      
      - name: Install opensource COBOL 4J
        run: |
          ./configure --prefix=/usr/ CFLAGS='-fprofile-arcs -ftest-coverage'
          make
          sudo make install

      - name: Run NIST test
        working-directory: tests/cobol85
        run: make test || true

      - name: Run other tests
        working-directory: tests
        run: |
          tests=("command-line-options" "data-rep" "i18n_sjis" "jp-compat" "run" "syntax" "cobj-idx" "file-lock" "file-lock2" "misc")
          for test in "${tests[@]}"; do
            ./"$test" || true
          done

      - name: Generate a coverage report
        working-directory: cobj
        run: |
          gcov -l ./*.gcda
          gcovr -r . \
            -e cobj-parser -e cobj-scanner -e cobj-pplex -e cobj-ppparse \
            -e parser.c -e parser.y -e scanner.l -e scanner.c -e pplex.l -e pplex.c -e ppparse.y -e ppparse.c \
            -e flag-help.def -e warning-help.def -e warning.def \
            --html-details --html-self-contained --html -o report.html --txt-metric=branch
          mkdir -p coverage-report
          cp ./*.html coverage-report

      - name: Archive a coverage report
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage-report
          path: cobj/coverage-report/