name: Create a Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  create-release:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Create a Release
      run: gh release create ${{ github.ref }} -F ReleaseNote.md