name: Javadoc

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Checkout opensource COBOL 4J
        uses: actions/checkout@v4
      
      - name: Run javadoc
        working-directory: libcobj 
        run: |
          ./gradlew javadoc