name: test on push

on:
  push:

env:
  CLASSPATH: ":/usr/lib/opensourcecobol4j/libcobj.jar"

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu:22.04"]
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}

  run-test-other:
    needs: build
    strategy:
      matrix:
        test_name: ["command-line-options", "data-rep", "i18n_sjis", "jp-compat", "run", "syntax", "cobj-idx"]
        os: ["ubuntu:22.04"]
    uses: ./.github/workflows/test-other.yml
    with:
      test-name: ${{ matrix.test_name }}
      os: ${{ matrix.os }}

  run-test-nist:
    needs: build
    strategy:
      matrix:
        test_name: ["IC", "IF", "IX", "NC", "OB", "RL", "SG", "SM", "SQ", "ST"]
        os: ["ubuntu:22.04"]
    uses: ./.github/workflows/test-nist.yml
    with:
      test-name: ${{ matrix.test_name }}
      check-result: true
      os: ${{ matrix.os }}

  run-test-nist-extra:
    needs: build
    strategy:
      matrix:
        test_name: ["CM", "DB", "RW"]
        os: ["ubuntu:22.04"]
    uses: ./.github/workflows/test-nist.yml
    with:
      test-name: ${{ matrix.test_name }}
      check-result: false
      os: ${{ matrix.os }}

  static-analysis:
    uses: ./.github/workflows/static-analysis.yml