name: test on push

on:
  push:
    paths-ignore:
      - '*.md'
      - 'ChangeLog'
      - 'NEWS'
      - 'README'
      - 'COPYING'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CLASSPATH: ":/usr/lib/opensourcecobol4j/libcobj.jar"

jobs:
  check-workflows:
    uses: ./.github/workflows/check-workflows.yml

  build:
    needs: check-workflows
    strategy:
      matrix:
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}

  run-test-other:
    needs: build
    strategy:
      matrix:
        test_name: ["command-line-options", "data-rep", "i18n_sjis", "jp-compat", "run", "syntax", "cobj-idx", "misc"]
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/test-other.yml
    with:
      test-name: ${{ matrix.test_name }}
      os: ${{ matrix.os }}

  run-test-nist:
    needs: build
    strategy:
      matrix:
        test_name: ["IC", "IF", "IX", "NC", "OB", "RL", "SG", "SM", "SQ", "ST"]
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/test-nist.yml
    with:
      test-name: ${{ matrix.test_name }}
      check-result: true
      os: ${{ matrix.os }}

  run-test-nist-extra:
    needs: build
    strategy:
      matrix:
        test_name: ["CM", "DB", "RW"]
        os: ["ubuntu:24.04"]
    uses: ./.github/workflows/test-nist.yml
    with:
      test-name: ${{ matrix.test_name }}
      check-result: false
      os: ${{ matrix.os }}

  build-gcc9:
    needs: check-workflows
    uses: ./.github/workflows/build-gcc9.yml

  javadoc:
    needs: check-workflows
    uses: ./.github/workflows/javadoc.yml

  MSBuild:
    needs: check-workflows
    uses: ./.github/workflows/msbuild.yml

  static-analysis:
    needs: check-workflows
    uses: ./.github/workflows/static-analysis.yml
