name: static analysis

on:
  workflow_call:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      # Checkout opensource COBOL
      - name: Checkout opensource COBOL 4J
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install static analysis tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format cppcheck

      - name: Install opensource COBOL 4J
        run: |
          sudo apt install -y build-essential bison flex gettext texinfo automake autoconf
          ./configure --prefix=/usr/
          make
          sudo make install

      - name: Check format with google-java-format and clang-format
        run: |
          ./check-format

      - name: Run SpotBugs (ignore results)
        run: |
          cd libcobj
          ./gradlew spotbugsMain || true

      - name: Run PMD
        run: |
          cd libcobj
          ./gradlew pmdMain

      - name: Run cppcheck (ignore results)
        run: |
          cd cobj && cppcheck cobj.c cobj.h codegen.c config.c error.c field.c pplex.c ppparse.c ppparse.h reserved.c tree.c tree.h typeck.c