name: static analysis

on:
  workflow_call:

permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      # Checkout opensource COBOL
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout opensource COBOL 4J
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install static analysis tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format cppcheck

      - name: Install opensource COBOL 4J
        run: |
          sudo apt install -y build-essential bison flex gettext texinfo autoconf
          ./configure --prefix=/usr/
          make
          sudo make install

      - name: Check format with google-java-format and clang-format
        run: |
          ./check-format

      - name: Run SpotBugs
        working-directory: libcobj
        run: |
          ./gradlew spotbugsMain

      - name: Run PMD
        working-directory: libcobj
        run: |
          ./gradlew pmdMain

      - name: Run cppcheck
        working-directory: cobj
        run: |
          ./cpp-check