name: ESQL UTF-8 tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

permissions:
  contents: read

env:
  CLASSPATH: ":/usr/lib/opensourcecobol4j/libcobj.jar"

jobs:
  test-esql-utf8:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.os }}

    services:
      postgres15:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: main_user
          POSTGRES_DB: testdb
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Get the artifact name
        run: echo "ARTIFACT_NAME=${{ inputs.os }}" | sed 's/:/-/g' >> "$GITHUB_ENV"

      - uses: actions/download-artifact@v8
        with:
          name: opensourcecobol4j-${{ env.ARTIFACT_NAME }}-opt_--enable-utf8

      - name: Install dependencies on Amazon Linux 2023
        if: inputs.os == 'amazonlinux:2023'
        run: |
          dnf -y update
          dnf install -y gcc make diffutils tar gzip

      - name: Install Java on Amazon Linux 2023
        if: inputs.os == 'amazonlinux:2023'
        run: |
          dnf install -y java-11-amazon-corretto-devel

      - uses: actions/setup-java@v5
        if: inputs.os != 'amazonlinux:2023'
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies on Ubuntu 24.04
        if: inputs.os == 'ubuntu:24.04'
        run: |
          apt-get update -y
          apt-get install -y build-essential

      - name: Install dependencies on AlmaLinux 9
        if: inputs.os == 'almalinux:9'
        run: |
          dnf -y update
          dnf install -y gcc make diffutils

      - name: Install opensource COBOL 4J
        run: |
          tar zxf opensourcecobol4j.tar.gz
          mv opensourcecobol4j/* .
          make install

      - name: Setup DB info
        working-directory: tests/
        run: |
          cat > embed_db_info.sh << 'DBEOF'
          DB_NAME=testdb
          DB_HOST=postgres15
          DB_PORT=5432
          DB_USER=main_user
          DB_PASSWORD=password
          TEMP_FILE=$(mktemp)
          cat $1 |
          sed -e "s/<|DB_NAME|>/${DB_NAME}/g" |
          sed -e "s/<|DB_HOST|>/${DB_HOST}/g" |
          sed -e "s/<|DB_PORT|>/${DB_PORT}/g" |
          sed -e "s/<|DB_USER|>/${DB_USER}/g" |
          sed -e "s/<|DB_PASSWORD|>/${DB_PASSWORD}/g" > ${TEMP_FILE}
          mv ${TEMP_FILE} $1
          DBEOF

      - name: Run ESQL UTF-8 tests
        id: esql-utf8
        working-directory: tests/
        run: ./esql-utf8 -j4

      - name: Upload test logs if tests fail
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: esql-utf8-test-${{ env.ARTIFACT_NAME }}-log
          path: |
            tests/esql-utf8.dir/
